# Generated by Django 4.2.7 on 2023-12-11 21:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="details",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
