# Generated by Django 4.1.3 on 2023-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='actions',
            field=models.CharField(choices=[('Hire', 'Hire'), ('Purchase', 'Purchase'), ('Hire & Purchase', 'Hire & Purchase')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used')], max_length=20),
        ),
    ]
