# Generated by Django 4.2.7 on 2023-12-13 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0004_vehicleorderrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="more_details",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
