# Generated by Django 4.2.7 on 2023-12-13 13:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("consultancy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancyproject",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
