# Generated by Django 4.1.3 on 2023-09-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_thumbnail'),
        ('cart', '0002_order_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
