# Generated by Django 4.2.7 on 2023-12-11 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_thumbnail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
