# Generated by Django 4.2.7 on 2023-12-13 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="details",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
